/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;
import model.user;
import service.userSV;
import com.formdev.flatlaf.FlatLightLaf;
import javax.swing.UIManager;
/**
 *
 * @author ASUS
 */
public class Cloud extends javax.swing.JFrame {

    public String version = "Version: 1.0.0.1";

    /**
     * Creates new form Cloud
     */
    public Cloud() {
        initComponents();
        versionshow.setText(version);
        // Khởi tạo JFrame và JPanel hoặc thành phần bạn cần
        this.setFocusable(true);  // Đảm bảo có thể nhận sự kiện bàn phím

        this.addKeyListener(new KeyAdapter() {
            public void keyPressed(KeyEvent e) {
                // Kiểm tra nếu phím Enter được nhấn
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    processLogin();
                }
            }
        });

        usernamefeild.addKeyListener(new KeyAdapter() {
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    processLogin();
                }
            }
        });

        passwordfeild.addKeyListener(new KeyAdapter() {
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    processLogin();
                }
            }
        });

    }

    private void processLogin() {
        String username = usernamefeild.getText();
        String password = String.valueOf(passwordfeild.getPassword());

        userSV userService = new userSV();
        user User = new user();

        if (userService.checkLogin(username, password)) {
            User = userService.findUserByUsername(username);
            if (User.getKind()==0) {
                new admin().setVisible(true);
                this.dispose();  // Đóng JFrame hiện tại
            } else if(User.getKind()==1){
                new home(username).setVisible(true);
                this.dispose();  // Đóng JFrame hiện tạii
            }
            else if(User.getKind()==2){
                
                this.dispose();  // Đóng JFrame hiện tạii
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "Sai thông tin đăng nhập!");
        }

//        if(!username.equals("")){
//            if (password.equals("tananhdeptrai")) {
//                if(username.equals("admin")){
//                    //String root="";
//                    new admin().setVisible(true);
//                    this.dispose();  // Đóng JFrame hiện tại
//                }
//                else{
//                    new home(username).setVisible(true);
//                    this.dispose();  // Đóng JFrame hiện tại
//                }
//            } else {
//                JOptionPane.showMessageDialog(this, "Mật khẩu sai!");
//            }
//        }
//        
//        else{
//            JOptionPane.showMessageDialog(this, "Vui lòng nhập username!");
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        signup_dialog = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jPasswordField2 = new javax.swing.JPasswordField();
        back_button = new javax.swing.JButton();
        dangky = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        versionshow_signup = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        usernamefeild = new javax.swing.JTextField();
        passwordfeild = new javax.swing.JPasswordField();
        signup_button = new javax.swing.JButton();
        signin_button = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        versionshow = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();

        signup_dialog.setTitle("Mega Space");
        signup_dialog.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        signup_dialog.setLocation(new java.awt.Point(300, 150));
        signup_dialog.setMinimumSize(new java.awt.Dimension(950, 585));
        signup_dialog.setResizable(false);
        signup_dialog.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(51, 102, 255));
        jPanel3.setMaximumSize(new java.awt.Dimension(950, 550));
        jPanel3.setMinimumSize(new java.awt.Dimension(950, 550));
        jPanel3.setPreferredSize(new java.awt.Dimension(950, 550));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI Semilight", 0, 16)); // NOI18N
        jLabel9.setText("Password:");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 90, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI Semilight", 0, 16)); // NOI18N
        jLabel10.setText("Full Name:");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 80, 30));
        jPanel4.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 210, 30));
        jPanel4.add(jPasswordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 210, 30));

        back_button.setBackground(new java.awt.Color(153, 255, 204));
        back_button.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        back_button.setText("Back to Login");
        back_button.setToolTipText("");
        back_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_buttonActionPerformed(evt);
            }
        });
        jPanel4.add(back_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, 120, 40));

        dangky.setBackground(new java.awt.Color(0, 255, 204));
        dangky.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        dangky.setText("Sign up");
        dangky.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dangkyActionPerformed(evt);
            }
        });
        jPanel4.add(dangky, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, 130, 40));

        jLabel11.setFont(new java.awt.Font("Script MT Bold", 1, 48)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 255));
        jLabel11.setText("Sign up");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, -1, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI Semilight", 0, 16)); // NOI18N
        jLabel17.setText("Email:");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 40, 30));
        jPanel4.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 210, 30));

        jLabel18.setFont(new java.awt.Font("Segoe UI Semilight", 0, 16)); // NOI18N
        jLabel18.setText("Number Phone:");
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 110, 30));
        jPanel4.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 210, 30));

        jLabel19.setFont(new java.awt.Font("Segoe UI Semilight", 0, 16)); // NOI18N
        jLabel19.setText("User Name:");
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 100, 30));
        jPanel4.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 210, 30));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, 420, 500));

        jLabel5.setFont(new java.awt.Font("Wide Latin", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Mega Space");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon("T:\\JavaNetbeans\\Cloud\\img\\removelogo.png")); // NOI18N
        jLabel7.setToolTipText("");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 230, 130));

        jLabel12.setForeground(new java.awt.Color(204, 255, 255));
        jLabel12.setText("Free 1024 MB per account");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 460, 170, 30));

        versionshow_signup.setForeground(new java.awt.Color(204, 255, 255));
        jPanel3.add(versionshow_signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 180, 20));

        jLabel22.setFont(new java.awt.Font("Script MT Bold", 1, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText(" Endless space, limitless possibilities");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 390, 60));

        signup_dialog.getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 550));

        jPanel5.setMaximumSize(new java.awt.Dimension(950, 585));
        jPanel5.setMinimumSize(new java.awt.Dimension(950, 585));
        jPanel5.setPreferredSize(new java.awt.Dimension(950, 585));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mega Space");
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(950, 585));
        setMinimumSize(new java.awt.Dimension(950, 585));
        setPreferredSize(new java.awt.Dimension(950, 585));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));
        jPanel1.setToolTipText("");
        jPanel1.setMaximumSize(new java.awt.Dimension(950, 550));
        jPanel1.setMinimumSize(new java.awt.Dimension(950, 550));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Password:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 90, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("User Name:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 100, 30));
        jPanel2.add(usernamefeild, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 210, 30));
        jPanel2.add(passwordfeild, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 210, 30));

        signup_button.setBackground(new java.awt.Color(153, 255, 255));
        signup_button.setText("Sign up");
        signup_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signup_buttonActionPerformed(evt);
            }
        });
        jPanel2.add(signup_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 120, 40));

        signin_button.setBackground(new java.awt.Color(0, 255, 255));
        signin_button.setText("Log in");
        signin_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signin_buttonActionPerformed(evt);
            }
        });
        jPanel2.add(signin_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, 130, 40));

        jLabel4.setFont(new java.awt.Font("Script MT Bold", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setText("Login");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, 420, 500));

        jLabel1.setFont(new java.awt.Font("Wide Latin", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Mega Space");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon("T:\\JavaNetbeans\\Cloud\\img\\removelogo.png")); // NOI18N
        jLabel6.setToolTipText("");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 230, 130));

        jLabel8.setForeground(new java.awt.Color(204, 255, 255));
        jLabel8.setText("Free 1024 MB per account");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 460, 170, 30));

        versionshow.setForeground(new java.awt.Color(204, 255, 255));
        jPanel1.add(versionshow, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 180, 20));

        jLabel21.setFont(new java.awt.Font("Script MT Bold", 1, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText(" Endless space, limitless possibilities");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 390, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 550));

        getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void signup_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signup_buttonActionPerformed
        // TODO add your handling code here:
        signup_dialog.setLocationRelativeTo(null);
        this.setVisible(false);
        signup_dialog.setVisible(true);
        versionshow_signup.setText(version);
    }//GEN-LAST:event_signup_buttonActionPerformed

    private void signin_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signin_buttonActionPerformed
        // TODO add your handling code here:
        processLogin();
    }//GEN-LAST:event_signin_buttonActionPerformed

    private void back_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_buttonActionPerformed
        // TODO add your handling code here:
        signup_dialog.setVisible(false);
        Cloud.this.setVisible(true);
    }//GEN-LAST:event_back_buttonActionPerformed

    private void dangkyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dangkyActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Lỗi hệ thống, hiện không thể đăng ký tài khoản!", "error", JOptionPane.CANCEL_OPTION);
    }//GEN-LAST:event_dangkyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cloud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cloud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cloud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cloud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cloud().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_button;
    private javax.swing.JButton dangky;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JPasswordField passwordfeild;
    private javax.swing.JButton signin_button;
    private javax.swing.JButton signup_button;
    private javax.swing.JDialog signup_dialog;
    private javax.swing.JTextField usernamefeild;
    private javax.swing.JLabel versionshow;
    private javax.swing.JLabel versionshow_signup;
    // End of variables declaration//GEN-END:variables
}
